### ISSUE TITLE
Estudar a comunicação bluetooth

### ISSUE THREAD

**Issue by matheusherique** [PI2-Parkinson/EsterAppAndroid#6]

**Comment by isaacborges** [comment]
This article might help [Android BLE](https://medium.com/@avigezerit/bluetooth-low-energy-on-android-22bc7310387a).

**Comment by isaacborges** [comment]
Não será utilizada mais o BLE. Segundo a equipe de eletrônica, será utilizado o módulo wireless da ESP32.
